apiVersion: v1
kind: Service
metadata:
  labels:
    app: register-app
  name: my-service
  namespace: my-register-ns
spec:
  type: NodePort
  ports:
    - port: 80 # The port the service is exposed on
      targetPort: 80 # The port your application is listening on
  selector:
    app: register-app
